### PR TITLE
API debugging

### PR DESCRIPTION
**Pull request by liwuyao**

### CODE REVIEW

**Comment by liwuyao** [comment]
API debugging

**Comment by chrislusf** [comment]
Works! 2 improvements to do:
* Resizing the browser does not affect the tree width.
* The directory size data is in bytes. The UI seems treating it as GB.

Screen Shot 2021-07-05 at 01 52 29

**Comment by chrislusf** [comment]
* 占比应该是把当前目录的大小除以根目录的大小。
* 文本改成英文？
* 根目录最好能网页刚载完就自动展开

**Comment by chrislusf** [comment]
* 根目录最好能网页刚载完就自动展开

**Pull request merged**
